fmt documents
algorand/algorand-sdk-testing pull request #151
Opened 2021-12-07 18:12 UTC by barnjamin

Just used the formatter to format the tables, should only be whitespace changes

2021-12-07 18:14 UTC, barnjamin commented on features/integration/dryrun.feature
> +      Scenarios:
This spacing is unexpected, I need to double check the syntax

2021-12-09 14:03 UTC, winder requested changes
LGTM. Could you add a comment to the README that describes how you ran the formatter?

2021-12-09 15:18 UTC, barnjamin commented
@winder I just used whatever is built into vscode, though I should probably write a small script to pull down something like https://github.com/antham/ghokin and format it

2021-12-14 16:25 UTC, winder approved these changes

2021-12-14 16:25 UTC, merged