Add tests for devmode timestamps
algorand/algorand-sdk-testing pull request #275
Opened 2023-04-21 16:30 UTC by algochoi

2023-04-21 18:37 UTC, tzaffi commented on features/integration/devmode.feature
> +    Then the timestamp offset should be 1234
Is line 9 purely testing `GET /v2/devmode/blocks/offset/` ? If so, maybe it's also worth adding a step that calls `GET v2/block/{round}` and verifies that the offset had the desired effect? Might be tricky to make it non-flaky though...

2023-04-21 18:37 UTC, tzaffi reviewed
Looks good. Just proposing an additional step (or two)

2023-04-24 15:28 UTC, winder commented
I don't think an integration test adds much safety here beyond whats already been done in the algod tests.

What do you think about adding the path/response unit tests and calling it a day?

For example: https://github.com/algorand/algorand-sdk-testing/pull/245/files

2023-04-24 16:20 UTC, tzaffi commented
> I don't think an integration test adds much safety here beyond whats already been done in the algod tests.
> 
> What do you think about adding the path/response unit tests and calling it a day?
> 
> For example: https://github.com/algorand/algorand-sdk-testing/pull/245/files

I think some kind of **E2E** in `go-algorand` or _integration_ test in one repo ought to exist showing that the devmode timestamps are behaving as expected. Maybe this already exists, but I didn't spot such a test in a brief search. Maybe add this test somewhere in [this file](https://github.com/algorand/go-algorand/blob/8fd6e702f2b319da5e404815f8af7a402e2a67f1/test/e2e-go/features/devmode/devmode_test.go#L33)?

2023-04-24 16:49 UTC, algochoi commented
Alternatively we could implement a full end to end test for devmode APIs for only one SDK (e.g. Python) under the @devmode integration tag and the rest can be tested with the path unit test?

2023-04-24 20:19 UTC, algochoi commented
> What do you think about adding the path/response unit tests and calling it a day?


Added path/response tests here: https://github.com/algorand/algorand-sdk-testing/pull/276

2023-04-27 13:54 UTC, winder requested changes
Based on our previous conversations, I think this can be closed. Let me know if you disagree and we can discuss in person.

2023-04-27 13:58 UTC, algochoi commented
Sounds good, I'll close this for now.

2023-04-27 13:58 UTC, closed without merging